"""tenho que estudar sqlalchemy

Revision ID: 0e1272288fcf
Revises: b0a32b0c2cf0
Create Date: 2025-02-02 16:19:37.593537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e1272288fcf'
down_revision: Union[str, None] = 'b0a32b0c2cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
