"""Adicionar cascade ao relacionamento Client-Ticket

Revision ID: 2332137b4887
Revises: 4724571f9bbf
Create Date: 2025-02-18 19:15:57.964855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2332137b4887'
down_revision: Union[str, None] = '4724571f9bbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
