"""mudança nos models

Revision ID: fe556bfb46e4
Revises: b9cb8c950398
Create Date: 2025-01-30 19:25:54.857069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe556bfb46e4'
down_revision: Union[str, None] = 'b9cb8c950398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'clients', ['phone'])
    op.create_unique_constraint(None, 'clients', ['company_name'])
    op.alter_column('tickets', 'solution',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'solution',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_constraint(None, 'clients', type_='unique')
    op.alter_column('clients', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
